/* eslint-disable @next/next/no-img-element */
"use client";
import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useMemo, useState } from "react";
import { DEFAULT_KIOSK_HEADLINE } from "../lib/app-settings";
import type { CategoryRailItem, OrderDraft, OrderRecord, Product, SeasonSchedule } from "./types";
import AppNav from "./AppNav";
import "../kiosk-flow.css";

type Step="products"|"cart"|"fulfillment"|"pickup-info"|"pickup-date"|"pickup-time"|"shipping-sender"|"shipping-recipient"|"shipping-address"|"shipping-date"|"payment"|"done";
type PostcodeData={zonecode:string;roadAddress:string;jibunAddress:string;autoJibunAddress:string;bname:string;buildingName:string;apartment:string};
type KakaoWindow=Window&{kakao?:{Postcode:new(options:{oncomplete:(data:PostcodeData)=>void;onclose?:()=>void})=>{open:()=>void}}};
const transition={duration:.24,ease:[.22,1,.36,1] as [number,number,number,number]};
const emptyDraft=():OrderDraft=>({cart:{},customItem:null,fulfillmentType:null,paymentMethod:null,buyerName:"",buyerPhone:"",recipientName:"",recipientPhone:"",postalCode:"",roadAddr:"",roadAddrReference:"",jibunAddr:"",detailAddr:"",addressMode:"search",pickupDate:"",pickupTime:"",shipDate:"",note:"",scheduleLabel:"",idempotencyKey:crypto.randomUUID()});
const won=(value:number)=>value.toLocaleString("ko-KR")+"원";
const parseIso=(value:string)=>{const [year,month,day]=value.split("-").map(Number);return new Date(Date.UTC(year,month-1,day))};
const isoFromDate=(date:Date)=>`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}-${String(date.getUTCDate()).padStart(2,"0")}`;
const todayInSeoul=()=>{const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),part=(type:string)=>parts.find(value=>value.type===type)?.value??"";return `${part("year")}-${part("month")}-${part("day")}`};
const koreanDate=(value:string)=>{if(!value)return "";const date=parseIso(value),weekdays=["일","월","화","수","목","금","토"];return `${date.getUTCMonth()+1}월 ${date.getUTCDate()}일 (${weekdays[date.getUTCDay()]})`};
const pickupTimes=Array.from({length:27},(_,index)=>{const minutes=8*60+index*30;return `${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`});

function normalizeDraft(value:Partial<OrderDraft>&{roadAddress?:string;detailAddress?:string}):OrderDraft{
 return {...emptyDraft(),...value,cart:value.cart??{},customItem:value.customItem??null,paymentMethod:value.paymentMethod??null,postalCode:value.postalCode??"",roadAddr:value.roadAddr??value.roadAddress??"",roadAddrReference:value.roadAddrReference??"",jibunAddr:value.jibunAddr??"",detailAddr:value.detailAddr??value.detailAddress??"",addressMode:value.addressMode??"search",pickupDate:value.pickupDate??"",pickupTime:value.pickupTime??"",shipDate:value.shipDate??""};
}
function Photo({product,large=false}:{product:Product;large?:boolean}){
 return <div className={"product-photo "+(large?"large":"")}>{product.imageUrl?<img src={product.imageUrl} alt={product.name}/>:<div className="photo-empty" role="img" aria-label={product.name+" 제품 사진 준비 중"}><span>▧</span><b>제품 사진</b><small>준비 중</small></div>}{product.badge&&<em>{product.badge}</em>}</div>;
}
function Quantity({value,onChange,big=false,max=null}:{value:number;onChange:(value:number)=>void;big?:boolean;max?:number|null}){
 const closed=max!==null&&max<=0,atMax=max!==null&&value>=max;
 return <div className={"quantity "+(big?"big":"")}><button disabled={value<=0} onClick={event=>{event.stopPropagation();onChange(Math.max(0,value-1))}} aria-label="수량 줄이기">−</button><b>{value}</b><button disabled={closed||atMax} onClick={event=>{event.stopPropagation();onChange(max===null?value+1:Math.min(max,value+1))}} aria-label="수량 늘리기">＋</button></div>;
}
function Field({label,value,onChange,placeholder,type="text",wide=false,error,readOnly=false}:{label:string;value:string;onChange:(value:string)=>void;placeholder:string;type?:string;wide?:boolean;error?:string;readOnly?:boolean}){
 return <label className={wide?"field wide":"field"}><span>{label}</span><input type={type} value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder} inputMode={type==="tel"?"numeric":undefined} aria-invalid={Boolean(error)} readOnly={readOnly}/>{error&&<small className="field-error">{error}</small>}</label>;
}

export default function KioskApp({categories}:{categories:CategoryRailItem[]}){
 const railCategories=categories.filter(item=>!item.isCustomOrderLink),customLinks=categories.filter(item=>item.isCustomOrderLink);
 const[products,setProducts]=useState<Product[]>([]),[season,setSeason]=useState<SeasonSchedule|null>(null),[headline,setHeadline]=useState(DEFAULT_KIOSK_HEADLINE),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 const[draft,setDraft]=useState<OrderDraft>(emptyDraft),[draftHydrated,setDraftHydrated]=useState(false),[step,setStep]=useState<Step>("products"),[direction,setDirection]=useState(1),[category,setCategory]=useState(railCategories[0]?.name??""),[detail,setDetail]=useState<Product|null>(null),[detailQty,setDetailQty]=useState(1),[submitting,setSubmitting]=useState(false),[submitError,setSubmitError]=useState(""),[completed,setCompleted]=useState<OrderRecord|null>(null);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{const saved=sessionStorage.getItem("jeongilpum-kiosk-draft");if(saved)try{const restored=normalizeDraft(JSON.parse(saved) as Partial<OrderDraft>),resume=new URLSearchParams(location.search).get("resume"),hasItems=Object.values(restored.cart).some(Boolean)||Boolean(restored.customItem);setDraft(restored);if(resume==="payment"&&restored.fulfillmentType==="onsite"&&restored.paymentMethod&&hasItems)setStep("payment");else if(resume==="cart"&&hasItems)setStep("cart")}catch{sessionStorage.removeItem("jeongilpum-kiosk-draft")};setDraftHydrated(true);fetch("/api/products",{cache:"no-store"}).then(response=>response.json() as Promise<{products?:Product[];activeSeason?:SeasonSchedule|null;appSettings?:{kioskHeadline?:string};error?:string}>).then(data=>{if(!data.products)throw new Error(data.error);setProducts(data.products);setSeason(data.activeSeason??null);setHeadline(data.appSettings?.kioskHeadline?.trim()||DEFAULT_KIOSK_HEADLINE)}).catch(()=>setLoadError("상품과 예약 일정을 불러오지 못했습니다. 연결을 확인하고 다시 시도해주세요.")).finally(()=>setLoading(false))});return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>{if(draftHydrated&&step!=="done")sessionStorage.setItem("jeongilpum-kiosk-draft",JSON.stringify(draft))},[draft,draftHydrated,step]);
 const selected=useMemo(()=>products.filter(product=>draft.cart[product.id]>0),[products,draft.cart]);
 const totalQty=selected.reduce((sum,product)=>sum+draft.cart[product.id],0)+(draft.customItem?1:0),total=selected.reduce((sum,product)=>sum+product.price*draft.cart[product.id],0)+(draft.customItem?.budgetAmount??0);
 const today=todayInSeoul(),minScheduleDate=season?(season.salesStartDate>today?season.salesStartDate:today):today,maxScheduleDate=season?.salesEndDate??"";
 const setQty=(id:string,value:number)=>setDraft(current=>{const product=products.find(item=>item.id===id),max=product?.remainingQuantity;return {...current,cart:{...current.cart,[id]:Math.max(0,max===null||max===undefined?value:Math.min(max,value))}}});
 const go=(next:Step,nextDirection=1)=>{setDirection(nextDirection);setStep(next);setSubmitError("")};
 const back=()=>{const paymentBack=draft.fulfillmentType==="onsite"?"fulfillment":draft.fulfillmentType==="pickup"?"pickup-time":"shipping-date",map:Partial<Record<Step,Step>>={cart:"products",fulfillment:"cart","pickup-info":"fulfillment","pickup-date":"pickup-info","pickup-time":"pickup-date","shipping-sender":"fulfillment","shipping-recipient":"shipping-sender","shipping-address":"shipping-recipient","shipping-date":"shipping-address",payment:paymentBack};go(map[step]??"products",-1)};
 const chooseFulfillment=(type:"onsite"|"pickup"|"shipping")=>{setDraft(current=>({...current,fulfillmentType:type,paymentMethod:null,buyerName:type==="onsite"?"":current.buyerName,buyerPhone:type==="onsite"?"":current.buyerPhone,scheduleLabel:type==="onsite"?"현장판매":type==="pickup"?(current.pickupDate&&current.pickupTime?koreanDate(current.pickupDate)+" · "+current.pickupTime:""):(current.shipDate?koreanDate(current.shipDate)+" 발송 예정":"")}));go(type==="onsite"?"payment":type==="pickup"?"pickup-info":"shipping-sender")};
 const submit=async()=>{if(submitting||!draft.paymentMethod)return;setSubmitting(true);setSubmitError("");try{const response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idempotencyKey:draft.idempotencyKey,buyerName:draft.buyerName,buyerPhone:draft.buyerPhone,fulfillmentType:draft.fulfillmentType,paymentMethod:draft.paymentMethod,pickupDate:draft.pickupDate,pickupTime:draft.pickupTime,shipDate:draft.shipDate,recipientName:draft.recipientName,recipientPhone:draft.recipientPhone,postalCode:draft.postalCode,roadAddr:draft.roadAddr,roadAddrReference:draft.roadAddrReference,jibunAddr:draft.jibunAddr,detailAddr:draft.detailAddr,note:draft.note,items:selected.map(product=>({productId:product.id,quantity:draft.cart[product.id]})),customItem:draft.customItem})}),data=await response.json() as {order?:OrderRecord;error?:string};if(response.status===401&&draft.fulfillmentType==="onsite"){sessionStorage.setItem("jeongilpum-kiosk-draft",JSON.stringify(draft));const localPreview=["localhost","127.0.0.1","[::1]"].includes(location.hostname);if(localPreview)throw new Error("로컬 미리보기에서는 현장판매를 저장할 수 없습니다. 운영 사이트에서 진행해주세요.");location.assign("/signin-with-chatgpt?return_to=%2Fkiosk%3Fresume%3Dpayment");return}if(!response.ok||!data.order)throw new Error(data.error||"주문을 접수하지 못했습니다.");setCompleted(data.order);sessionStorage.removeItem("jeongilpum-kiosk-draft");go("done")}catch(error){setSubmitError(error instanceof Error?error.message:"주문이 아직 접수되지 않았습니다.")}finally{setSubmitting(false)}};
 const reset=()=>{setDraft(emptyDraft());setCompleted(null);go("products",-1)};
 const filtered=products.filter(product=>product.category===category);
 return <div className="kiosk-app">
  <header className="kiosk-header"><a className="kiosk-brand" href="/kiosk"><img className="kiosk-brand-logo" src="/jeongilpum-logo.png" alt="정일품 정육식당 로고"/><div><b>정일품 정육식당</b></div></a><div className="kiosk-title"><b>{headline}</b></div><button className="cart-indicator" onClick={()=>totalQty&&go("cart")} aria-label={"장바구니 "+totalQty+"개"}>장바구니 <b>{totalQty}</b></button></header>
  <AppNav current="kiosk"/>
  <AnimatePresence mode="wait" custom={direction}>
   {step==="products"?<motion.div key="products" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={transition} className="product-step">
    <aside className="category-rail">{railCategories.map(item=><button key={item.id} className={(category===item.name?"active ":"")+(item.railVariant==="single"?"single":"with-assist")} onClick={()=>setCategory(item.name)}><strong className={item.railVariant==="omeat"?"category-name omeat":"category-name"}>{item.railLabel}</strong>{item.railAssist?<small className={item.railVariant==="omeat"?"category-assist omeat":"category-assist"}>{item.railAssist}</small>:null}</button>)}{customLinks.map(item=><a key={item.id} className="custom-order-link" href="/kiosk/custom"><strong>{item.railLabel}</strong><small>{item.railAssist}</small></a>)}</aside>
    <section className="product-pane"><div className="pane-heading"><div><small>{category.toUpperCase()}</small><h1>{category}</h1></div><span>{filtered.length}개 상품</span></div>{loading?<div className="product-loading">상품을 준비하고 있습니다…</div>:loadError?<div className="product-error"><b>상품 연결이 필요합니다</b><span>{loadError}</span><button onClick={()=>location.reload()}>다시 시도</button></div>:<div className="product-grid">{filtered.map(product=><button className="product-card" key={product.id} onClick={()=>{setDetail(product);setDetailQty(Math.max(1,draft.cart[product.id]||1))}}><Photo product={product}/><div className="product-copy"><small>{product.customerDisplayWeight||product.category}</small><h2>{product.name}</h2><p>{product.subtitle}</p><strong>{won(product.price)}</strong>{product.remainingQuantity!==null&&<em className={product.remainingQuantity===0?"availability closed":"availability"}>{product.remainingQuantity===0?"오늘 예약마감":`오늘 ${product.remainingQuantity}세트 남음`}</em>}<Quantity value={draft.cart[product.id]||0} max={product.remainingQuantity} onChange={value=>setQty(product.id,value)}/></div></button>)}</div>}</section>
    <div className="kiosk-orderbar"><div><span>선택 <b>{totalQty}</b>세트</span><strong>{won(total)}</strong></div><button disabled={!totalQty} onClick={()=>go("cart")}>주문하기 <span>→</span></button></div>
   </motion.div>:<FlowStep key={step} step={step} direction={direction} back={back}>
    {step==="cart"&&<CartStep products={selected} draft={draft} setQty={setQty} totalQty={totalQty} total={total} next={()=>go("fulfillment")}/>}
    {step==="fulfillment"&&<Fulfillment choose={chooseFulfillment}/>}
    {step==="pickup-info"&&<InfoStep title="주문자 정보를 알려주세요" description="방문수령 안내에 필요한 정보입니다." draft={draft} setDraft={setDraft} next={()=>go("pickup-date")} valid={draft.buyerName.trim().length>0&&draft.buyerPhone.replace(/\D/g,"").length>=10}/>}
    {step==="pickup-date"&&<ScheduleDateStep type="pickup" value={draft.pickupDate} minDate={minScheduleDate} maxDate={maxScheduleDate} setValue={value=>setDraft(current=>({...current,pickupDate:value,scheduleLabel:current.pickupTime?`${koreanDate(value)} · ${current.pickupTime}`:koreanDate(value)}))} next={()=>go("pickup-time")}/>}
    {step==="pickup-time"&&<PickupTime draft={draft} setDraft={setDraft} next={()=>go("payment")}/>}
    {step==="shipping-sender"&&<InfoStep title="보내는 분은 누구인가요?" description="주문 확인 연락을 드릴 정보를 입력해주세요." draft={draft} setDraft={setDraft} next={()=>go("shipping-recipient")} valid={draft.buyerName.trim().length>0&&draft.buyerPhone.replace(/\D/g,"").length>=10}/>}
    {step==="shipping-recipient"&&<RecipientStep draft={draft} setDraft={setDraft} next={()=>go("shipping-address")}/>}
    {step==="shipping-address"&&<AddressStep draft={draft} setDraft={setDraft} next={()=>go("shipping-date")}/>}
    {step==="shipping-date"&&<ScheduleDateStep type="shipping" value={draft.shipDate} minDate={minScheduleDate} maxDate={maxScheduleDate} setValue={value=>setDraft(current=>({...current,shipDate:value,scheduleLabel:`${koreanDate(value)} 발송 예정`}))} next={()=>go("payment")}/>}
    {step==="payment"&&<PaymentStep draft={draft} setDraft={setDraft} products={selected} totalQty={totalQty} total={total} submitting={submitting} error={submitError} submit={submit}/>}
    {step==="done"&&<Done order={completed} reset={reset}/>}
   </FlowStep>}
  </AnimatePresence>
  <AnimatePresence>{detail&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={transition} role="button" tabIndex={0} aria-label="상품 상세 닫기" onKeyDown={event=>{if(event.key==="Escape"||event.key==="Enter")setDetail(null)}} onMouseDown={()=>setDetail(null)}><motion.section className="product-modal" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.94}} transition={transition} onMouseDown={event=>event.stopPropagation()} role="dialog" aria-modal="true"><button className="modal-x" onClick={()=>setDetail(null)}>×</button><Photo product={detail} large/><div className="modal-copy"><small>{detail.category}</small><h2>{detail.name}</h2><strong>{won(detail.price)}</strong><p>{detail.description}</p><dl><div><dt>구성 / 중량</dt><dd>{detail.customerDisplayWeight||detail.subtitle}</dd></div></dl>{detail.remainingQuantity!==null&&<em className={detail.remainingQuantity===0?"availability closed":"availability"}>{detail.remainingQuantity===0?"오늘 예약마감":`오늘 ${detail.remainingQuantity}세트 남음`}</em>}<Quantity big value={detailQty} max={detail.remainingQuantity} onChange={setDetailQty}/><button className="main-cta" disabled={detail.remainingQuantity===0} onClick={()=>{setQty(detail.id,detailQty);setDetail(null)}}>{detail.remainingQuantity===0?"오늘 예약마감":"장바구니 담기"} <span>{detail.remainingQuantity===0?"":"＋"}</span></button></div></motion.section></motion.div>}</AnimatePresence>
 </div>;
}

function FlowStep({children,step,direction,back}:{children:React.ReactNode;step:Step;direction:number;back:()=>void}){
 const progress:Record<Step,number>={products:0,cart:10,fulfillment:20,"pickup-info":35,"pickup-date":50,"pickup-time":68,"shipping-sender":32,"shipping-recipient":45,"shipping-address":58,"shipping-date":72,payment:88,done:100};
 return <motion.section className="flow-shell" custom={direction} initial={{opacity:0,x:direction*70}} animate={{opacity:1,x:0}} exit={{opacity:0,x:direction*-70}} transition={transition}><header className="flow-header">{step!=="done"?<button onClick={back} aria-label="이전 단계">← <span>이전</span></button>:<span/>}<div className="flow-progress"><i style={{width:progress[step]+"%"}}/></div><span>{step==="done"?"접수 완료":"주문 진행"}</span></header><div className="flow-content">{children}</div>{step!=="done"&&<button className="flow-back-bottom" onClick={back}>← 이전 단계로</button>}</motion.section>;
}
function CartStep({products,draft,setQty,totalQty,total,next}:{products:Product[];draft:OrderDraft;setQty:(id:string,value:number)=>void;totalQty:number;total:number;next:()=>void}){
 return <div className="flow-card"><div className="flow-heading"><small>STEP 1</small><h1>주문 상품을 확인해주세요</h1><p>수량과 상품이 맞는지 한 번 더 확인합니다.</p></div><div className="cart-review">{products.map(product=><article key={product.id}><Photo product={product}/><div><h2>{product.name}</h2><span>{won(product.price)}</span></div><Quantity big value={draft.cart[product.id]} max={product.remainingQuantity} onChange={value=>setQty(product.id,value)}/></article>)}{draft.customItem&&<article className="custom-cart-item"><div><small>맞춤주문</small><h2>맞춤주문</h2><span>{draft.customItem.budgetOption} · {won(draft.customItem.budgetAmount)}</span></div><a href="/kiosk/custom">내용 수정</a></article>}</div><div className="flow-total"><span>총 {totalQty}세트</span><b>{won(total)}</b></div><button className="main-cta" disabled={!totalQty} onClick={next}>다음 <span>→</span></button></div>;
}
function Fulfillment({choose}:{choose:(type:"onsite"|"pickup"|"shipping")=>void}){
 return <div className="flow-card"><div className="flow-heading center"><small>STEP 2</small><h1>수령 방식을 선택해주세요</h1><p>예약 주문은 방문수령 또는 택배발송으로 접수합니다.</p></div><div className="fulfillment-customer-options"><button onClick={()=>choose("pickup")}><b>방문수령</b><small>예약 후 매장에서 받기</small></button><button onClick={()=>choose("shipping")}><b>택배발송</b><small>예약 후 원하는 곳으로 보내기</small></button></div><section className="onsite-sale-zone" aria-label="직원 전용 현장판매"><div className="onsite-sale-copy"><em>직원 전용</em><b>바로 판매 기록</b><small>고객정보 입력 없이 결제와 매출을 기록합니다.</small></div><button className="onsite-sale-option" onClick={()=>choose("onsite")}><b>현장판매</b><small>결제방식 선택으로 이동</small></button></section></div>;
}
function InfoStep({title,description,draft,setDraft,next,valid}:{title:string;description:string;draft:OrderDraft;setDraft:React.Dispatch<React.SetStateAction<OrderDraft>>;next:()=>void;valid:boolean}){
 const[attempted,setAttempted]=useState(false),nameValid=draft.buyerName.trim().length>0,phoneValid=draft.buyerPhone.replace(/\D/g,"").length>=10;
 const handleNext=()=>{if(valid){next();return}setAttempted(true)};
 return <div className="flow-card narrow"><div className="flow-heading"><small>고객정보</small><h1>{title}</h1><p>{description}</p></div><div className="form-stack"><Field label="주문자명 또는 회사명" value={draft.buyerName} onChange={value=>setDraft(current=>({...current,buyerName:value}))} placeholder="개인 이름 또는 회사명을 입력해주세요" error={attempted&&!nameValid?"주문자 이름 또는 회사명을 입력해주세요.":undefined}/><Field label="연락처" type="tel" value={draft.buyerPhone} onChange={value=>setDraft(current=>({...current,buyerPhone:value}))} placeholder="010-0000-0000" error={attempted&&!phoneValid?"휴대전화 번호를 숫자 10자리 이상 입력해주세요.":undefined}/><Field label="요청사항 (선택)" wide value={draft.note} onChange={value=>setDraft(current=>({...current,note:value}))} placeholder="예: 지방을 적게 부탁드립니다"/></div><div className={valid?"form-status ready":"form-status"}><span>{nameValid?"✓":"○"} 주문자명 또는 회사명</span><span>{phoneValid?"✓":"○"} 연락처 10자리 이상</span></div><button className="main-cta" onClick={handleNext}>다음 <span>→</span></button></div>;
}
function Calendar({value,minDate,maxDate,onSelect,disabledDates=[]}:{value:string;minDate:string;maxDate:string;onSelect:(value:string)=>void;disabledDates?:string[]}){
 const initialMonth=(value||minDate).slice(0,7),[month,setMonth]=useState(initialMonth),today=todayInSeoul();
 if(!minDate||!maxDate||minDate>maxDate)return <div className="schedule-unavailable">현재 선택 가능한 예약 날짜가 없습니다.</div>;
 const [year,monthNumber]=month.split("-").map(Number),first=new Date(Date.UTC(year,monthNumber-1,1)),daysInMonth=new Date(Date.UTC(year,monthNumber,0)).getUTCDate(),leading=first.getUTCDay(),cells=[...Array.from({length:leading},()=>null),...Array.from({length:daysInMonth},(_,index)=>index+1)];
 const previous=new Date(Date.UTC(year,monthNumber-2,1)),next=new Date(Date.UTC(year,monthNumber,1)),previousMonth=isoFromDate(previous).slice(0,7),nextMonth=isoFromDate(next).slice(0,7),minMonth=minDate.slice(0,7),maxMonth=maxDate.slice(0,7);
 return <section className="schedule-calendar" aria-label="예약 날짜 달력"><header><button onClick={()=>setMonth(previousMonth)} disabled={month<=minMonth} aria-label="이전 달">←</button><b>{year}년 {monthNumber}월</b><button onClick={()=>setMonth(nextMonth)} disabled={month>=maxMonth} aria-label="다음 달">→</button></header><div className="calendar-weekdays">{["일","월","화","수","목","금","토"].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-days">{cells.map((day,index)=>{if(day===null)return <span key={"empty-"+index}/>;const date=`${year}-${String(monthNumber).padStart(2,"0")}-${String(day).padStart(2,"0")}`,disabled=date<minDate||date>maxDate||disabledDates.includes(date);return <button key={date} disabled={disabled} className={[date===today?"today":"",value===date?"selected":"",disabled?"closed":""].filter(Boolean).join(" ")} aria-pressed={value===date} onClick={()=>onSelect(date)}><span>{day}</span>{date===today&&<small>오늘</small>}{value===date&&<small>✓ 선택</small>}{disabled&&date>=minDate&&date<=maxDate?<small>예약마감</small>:null}</button>})}</div></section>;
}
function ScheduleDateStep({type,value,minDate,maxDate,setValue,next}:{type:"pickup"|"shipping";value:string;minDate:string;maxDate:string;setValue:(value:string)=>void;next:()=>void}){
 const shipping=type==="shipping";
 return <div className="flow-card narrow"><div className="flow-heading"><small>{shipping?"택배발송":"방문수령"}</small><h1>{shipping?"상품을 발송할 날짜를 선택해주세요.":"방문 날짜를 선택해주세요."}</h1><p>{shipping?"택배사 사정에 따라 도착일은 달라질 수 있습니다.":"선택한 날짜에 맞춰 상품을 준비하겠습니다."}</p></div><Calendar value={value} minDate={minDate} maxDate={maxDate} onSelect={setValue}/>{value&&<div className="selected-schedule"><span>선택한 날짜</span><b>{koreanDate(value)}</b></div>}<button className="main-cta" disabled={!value} onClick={next}>{shipping?"결제방식 선택":"시간 선택"} <span>→</span></button></div>;
}
function PickupTime({draft,setDraft,next}:{draft:OrderDraft;setDraft:React.Dispatch<React.SetStateAction<OrderDraft>>;next:()=>void}){
 return <div className="flow-card narrow"><div className="flow-heading"><small>방문수령</small><h1>방문 시간을 선택해주세요.</h1><p>{koreanDate(draft.pickupDate)} · 08:00부터 21:00까지 30분 단위로 선택할 수 있습니다.</p></div><div className="pickup-time-grid">{pickupTimes.map(time=><button key={time} className={draft.pickupTime===time?"selected":""} onClick={()=>setDraft(current=>({...current,pickupTime:time,scheduleLabel:`${koreanDate(current.pickupDate)} · ${time}`}))}>{time}</button>)}</div><button className="main-cta" disabled={!draft.pickupTime} onClick={next}>결제방식 선택 <span>→</span></button></div>;
}
function RecipientStep({draft,setDraft,next}:{draft:OrderDraft;setDraft:React.Dispatch<React.SetStateAction<OrderDraft>>;next:()=>void}){
 const valid=draft.recipientName.trim().length>0&&draft.recipientPhone.replace(/\D/g,"").length>=10;
 return <div className="flow-card narrow"><div className="flow-heading"><small>택배 2/4</small><h1>받는 분을 알려주세요</h1><p>배송 안내에 필요한 정보입니다.</p></div><div className="form-stack"><Field label="받는 분 성함" value={draft.recipientName} onChange={value=>setDraft(current=>({...current,recipientName:value}))} placeholder="받는 분 성함 또는 회사명"/><Field label="받는 분 연락처" type="tel" value={draft.recipientPhone} onChange={value=>setDraft(current=>({...current,recipientPhone:value}))} placeholder="010-0000-0000"/></div><button className="main-cta" disabled={!valid} onClick={next}>주소 입력 <span>→</span></button></div>;
}
function loadPostcode(onComplete:(data:PostcodeData)=>void,onError:()=>void){
 const kakaoWindow=window as KakaoWindow,start=()=>{if(!kakaoWindow.kakao?.Postcode){onError();return}new kakaoWindow.kakao.Postcode({oncomplete:onComplete}).open()};
 if(kakaoWindow.kakao?.Postcode){start();return}
 const existing=document.getElementById("kakao-postcode-script") as HTMLScriptElement|null;
 if(existing){existing.addEventListener("load",start,{once:true});existing.addEventListener("error",onError,{once:true});return}
 const script=document.createElement("script");script.id="kakao-postcode-script";script.src="https://t1.kakaocdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js";script.async=true;script.addEventListener("load",start,{once:true});script.addEventListener("error",onError,{once:true});document.head.appendChild(script);
}
function AddressStep({draft,setDraft,next}:{draft:OrderDraft;setDraft:React.Dispatch<React.SetStateAction<OrderDraft>>;next:()=>void}){
 const[error,setError]=useState(""),manual=draft.addressMode==="manual",postalValid=/^\d{5}$/.test(draft.postalCode),valid=postalValid&&draft.roadAddr.trim().length>=5&&draft.detailAddr.trim().length>0;
 const search=()=>{setError("");loadPostcode(data=>{const references:string[]=[];if(data.bname&&/[동로가]$/.test(data.bname))references.push(data.bname);if(data.buildingName&&data.apartment==="Y")references.push(data.buildingName);setDraft(current=>({...current,addressMode:"search",postalCode:data.zonecode,roadAddr:data.roadAddress||data.jibunAddress,roadAddrReference:references.join(", "),jibunAddr:data.jibunAddress||data.autoJibunAddress||""}));setError("")},()=>setError("주소검색을 불러오지 못했습니다. 직접 입력을 이용해주세요."))};
 return <div className="flow-card narrow"><div className="flow-heading"><small>택배 3/4</small><h1>배송 주소를 확인해주세요</h1><p>참고항목은 실제 배송주소에 자동으로 합치지 않습니다.</p></div>{!manual?<><button className="postcode-search-button" onClick={search}>도로명주소 검색</button>{draft.roadAddr&&<article className="address-result-card"><small>선택한 주소</small><b>[{draft.postalCode}] {draft.roadAddr}</b>{draft.jibunAddr&&<span>지번: {draft.jibunAddr}</span>}{draft.roadAddrReference&&<span>참고: {draft.roadAddrReference}</span>}</article>}<button className="direct-address-button" onClick={()=>setDraft(current=>({...current,addressMode:"manual"}))}>주소를 직접 입력할게요</button></>:<><div className="manual-address-notice">직접 입력한 주소입니다. 배송 전 주소를 다시 확인해주세요.</div><div className="form-stack"><Field label="우편번호" value={draft.postalCode} onChange={value=>setDraft(current=>({...current,postalCode:value.replace(/\D/g,"").slice(0,5)}))} placeholder="5자리 우편번호"/><Field label="도로명 또는 지번 기본주소" value={draft.roadAddr} onChange={value=>setDraft(current=>({...current,roadAddr:value}))} placeholder="시/도, 시/군/구, 도로명 또는 지번"/><Field label="지번주소 (선택)" wide value={draft.jibunAddr} onChange={value=>setDraft(current=>({...current,jibunAddr:value}))} placeholder="보조 확인용 지번주소"/></div><button className="direct-address-button" onClick={()=>setDraft(current=>({...current,addressMode:"search"}))}>주소검색으로 돌아가기</button></>}{error&&<div className="address-error" role="alert">{error}</div>}<Field label="상세주소" value={draft.detailAddr} onChange={value=>setDraft(current=>({...current,detailAddr:value}))} placeholder="동·호수 또는 상세 위치" error={draft.postalCode&&!postalValid?"우편번호 5자리를 확인해주세요.":undefined}/><button className="main-cta" disabled={!valid} onClick={next}>발송일 선택 <span>→</span></button></div>;
}
function PaymentStep({draft,setDraft,products,totalQty,total,submitting,error,submit}:{draft:OrderDraft;setDraft:React.Dispatch<React.SetStateAction<OrderDraft>>;products:Product[];totalQty:number;total:number;submitting:boolean;error:string;submit:()=>void}){
 const onsite=draft.fulfillmentType==="onsite",shipping=draft.fulfillmentType==="shipping",methods=[{value:"card" as const,label:"카드",description:onsite?"카드 결제 완료":"카드 결제 예정"},{value:"cash" as const,label:"현금",description:onsite?"현금 수납 완료":"현금 결제 예정"},{value:"bank_transfer" as const,label:"계좌이체",description:onsite?"입금 확인 완료":"계좌이체 예정"},...(onsite?[]:[{value:"later" as const,label:"나중에 결정",description:"실제 결제 시 직원이 기록"}])];
 return <div className="flow-card review-card"><div className="flow-heading"><small>FINAL · PAYMENT</small><h1>결제방식을 선택해주세요</h1><p>{onsite?"고객정보 없이 선택한 결제수단과 판매금액을 바로 기록합니다.":"선택한 방식은 결제 예정 정보이며, 실제 입금은 직원 확인 후 장부에 기록합니다."}</p></div><div className="payment-method-options">{methods.map(method=><button key={method.value} className={draft.paymentMethod===method.value?"selected":""} aria-pressed={draft.paymentMethod===method.value} onClick={()=>setDraft(current=>({...current,paymentMethod:method.value}))}><b>{method.label}</b><small>{method.description}</small></button>)}</div>{shipping&&<section className="shipping-address-review"><small>실제 배송에 사용될 주소</small><strong>[{draft.postalCode}]</strong><b>{draft.roadAddr}</b><b>{draft.detailAddr}</b>{draft.jibunAddr&&<span>지번: {draft.jibunAddr}</span>}{draft.addressMode==="manual"&&<em>직접 입력한 주소입니다. 배송주소를 다시 확인해주세요.</em>}</section>}<div className="review-list"><section><h3>주문 상품</h3>{products.map(product=><p key={product.id}><span>{product.name} × {draft.cart[product.id]}</span><b>{won(product.price*draft.cart[product.id])}</b></p>)}{draft.customItem&&<div className="custom-review-item"><h3>맞춤주문</h3><p><span>예산</span><b>{draft.customItem.budgetOption} · {won(draft.customItem.budgetAmount)}</b></p><p><span>요청사항</span><b>{draft.customItem.request||"별도 요청 없음"}</b></p></div>}</section><section><h3>{onsite?"현장판매":shipping?"택배발송":"방문수령"}</h3>{onsite?<p><span>고객정보</span><b>미기입 현장판매</b></p>:<p><span>고객</span><b>{draft.buyerName} · {draft.buyerPhone}</b></p>}{shipping&&<p><span>받는 분</span><b>{draft.recipientName} · {draft.recipientPhone}</b></p>}{!onsite&&<p><span>{shipping?"발송일":"방문일시"}</span><b>{draft.scheduleLabel}</b></p>}{onsite&&<p><span>판매상태</span><b>결제와 함께 판매완료</b></p>}{draft.note&&<p><span>요청사항</span><b>{draft.note}</b></p>}</section></div><div className="flow-total"><span>총 {totalQty}세트</span><b>{won(total)}</b></div>{error&&<div className="submit-error"><b>{onsite?"현장판매가 아직 기록되지 않았습니다":"주문이 아직 접수되지 않았습니다"}</b><span>{error}</span>{onsite&&error.includes("로그인")&&<a href="/signin-with-chatgpt?return_to=/kiosk" target="_top">직원 로그인 후 계속</a>}</div>}<button className="main-cta" disabled={submitting||!draft.paymentMethod} onClick={submit}>{submitting?(onsite?"판매를 기록하고 있습니다…":"주문을 접수하고 있습니다…"):(onsite?"현장판매 기록":"주문 접수")}<span>{submitting?"":"→"}</span></button><small className="idempotency-note">같은 주문과 결제가 중복 기록되지 않도록 안전하게 확인합니다.</small></div>;
}
function Done({order,reset}:{order:OrderRecord|null;reset:()=>void}){
 const onsite=order?.fulfillmentType==="onsite";
 return <div className="done-card"><div className="done-mark">✓</div><small>{onsite?"SALE COMPLETE":"ORDER COMPLETE"}</small><h1>{onsite?"현장판매가 기록되었습니다":"주문 접수가 완료되었습니다"}</h1><p>{onsite?<>상품 판매와 결제내역이 고객 장부에 반영되었습니다.</>:<>주문이 정상적으로 접수되었습니다.<br/>실제 결제 확인은 직원이 도와드립니다.</>}</p><div className="receipt"><span>주문번호</span><b>{order?.orderNo||"-"}</b><span>판매·수령 방식</span><b>{onsite?"현장판매":order?.fulfillmentType==="pickup"?"방문수령":"택배발송"}</b><span>{onsite?"판매시점":"예정 일정"}</span><b>{order?.scheduleLabel||"-"}</b></div><button className="main-cta" onClick={reset}>새 주문 시작하기 <span>→</span></button></div>;
}
