import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const categories = sqliteTable("categories", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  railOrder: integer("rail_order"),
  railLabel: text("rail_label").notNull(),
  railAssist: text("rail_assist"),
  railVariant: text("rail_variant").notNull().default("default"),
  isCustomOrderLink: integer("is_custom_order_link", { mode: "boolean" }).notNull().default(false),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("idx_categories_name").on(table.name),
  index("idx_categories_active_sort_order").on(table.active, table.sortOrder),
  check("categories_rail_variant_valid", sql`${table.railVariant} in ('default', 'single', 'omeat')`),
]);

export const products = sqliteTable("products", {
  id: text("id").primaryKey(),
  category: text("category").notNull().references(() => categories.name, { onUpdate: "cascade" }),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  subtitle: text("subtitle").notNull().default(""),
  description: text("description").notNull().default(""),
  price: integer("price").notNull(),
  displayWeight: text("display_weight"),
  imageUrl: text("image_url"),
  badge: text("badge"),
  dailyLimit: integer("daily_limit"),
  sortOrder: integer("sort_order").notNull().default(0),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_products_active_sort_order").on(table.active, table.sortOrder),
  index("idx_products_category").on(table.category),
  check("products_daily_limit_positive", sql`${table.dailyLimit} is null or ${table.dailyLimit} >= 0`),
]);

export const orders = sqliteTable("orders", {
  id: text("id").primaryKey(),
  orderNo: text("order_no").notNull(),
  buyerName: text("buyer_name").notNull(),
  buyerPhone: text("buyer_phone").notNull(),
  paymentStatus: text("payment_status").notNull().default("unpaid"),
  paidAmount: integer("paid_amount").notNull().default(0),
  totalAmount: integer("total_amount").notNull(),
  customerArrivedAt: text("customer_arrived_at"),
  customerNote: text("customer_note").notNull().default(""),
  idempotencyKey: text("idempotency_key").notNull(),
  version: integer("version").notNull().default(1),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("idx_orders_idempotency").on(table.idempotencyKey),
  index("idx_orders_buyer_phone").on(table.buyerPhone),
  check("orders_payment_status_valid", sql`${table.paymentStatus} in ('unpaid', 'partial', 'paid')`),
  check("orders_paid_amount_nonnegative", sql`${table.paidAmount} >= 0`),
  check("orders_total_amount_nonnegative", sql`${table.totalAmount} >= 0`),
]);

export const workItems = sqliteTable("work_items", {
  id: text("id").primaryKey(),
  orderId: text("order_id").notNull().references(() => orders.id),
  productId: text("product_id").notNull().references(() => products.id),
  productNameSnapshot: text("product_name_snapshot").notNull(),
  unitPriceSnapshot: integer("unit_price_snapshot").notNull(),
  quantity: integer("quantity").notNull(),
  lineTotal: integer("line_total").notNull(),
  deliveryMethod: text("delivery_method").notNull(),
  dueAt: text("due_at").notNull(),
  workStatus: text("work_status").notNull().default("received"),
  recipientName: text("recipient_name"),
  recipientPhone: text("recipient_phone"),
  postalCode: text("postal_code"),
  roadAddr: text("road_addr"),
  roadAddrReference: text("road_addr_reference"),
  jibunAddr: text("jibun_addr"),
  detailAddr: text("detail_addr"),
  customizationJson: text("customization_json"),
  note: text("note").notNull().default(""),
  version: integer("version").notNull().default(1),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_work_items_order").on(table.orderId),
  index("idx_work_items_due_status").on(table.dueAt, table.workStatus),
  index("idx_work_items_product_due").on(table.productId, table.dueAt),
  check("work_items_quantity_positive", sql`${table.quantity} >= 0`),
  check("work_items_line_total_nonnegative", sql`${table.lineTotal} >= 0`),
  check("work_items_delivery_method_valid", sql`${table.deliveryMethod} in ('onsite_sale', 'onsite_reservation', 'delivery')`),
  check("work_items_status_valid", sql`${table.workStatus} in ('received', 'confirmed', 'in_progress', 'ready', 'completed', 'cancelled')`),
]);

export const workItemEvents = sqliteTable("work_item_events", {
  id: text("id").primaryKey(),
  workItemId: text("work_item_id").references(() => workItems.id, { onDelete: "set null" }),
  orderId: text("order_id").notNull().references(() => orders.id),
  eventType: text("event_type").notNull(),
  fromValue: text("from_value"),
  toValue: text("to_value"),
  actor: text("actor").notNull(),
  createdAt: text("created_at").notNull(),
}, (table) => [
  index("idx_work_item_events_work_item_created").on(table.workItemId, table.createdAt),
  index("idx_work_item_events_order_created").on(table.orderId, table.createdAt),
]);

export const traceabilityRecords = sqliteTable("traceability_records", {
  traceabilityNo: text("traceability_no").primaryKey(),
  lastRawScan: text("last_raw_scan").notNull(),
  origin: text("origin").notNull().default(""),
  slaughterhouse: text("slaughterhouse").notNull().default(""),
  cattleType: text("cattle_type").notNull().default(""),
  grade: text("grade").notNull().default(""),
  source: text("source").notNull().default("manual"),
  verifiedAt: text("verified_at"),
  lastUsedBy: text("last_used_by").notNull(),
  lastUsedAt: text("last_used_at").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [index("idx_traceability_recent_worker").on(table.lastUsedBy, table.lastUsedAt)]);

export const productionBatches = sqliteTable("production_batches", {
  id: text("id").primaryKey(),
  productionDate: text("production_date").notNull(),
  parentBatchId: text("parent_batch_id"),
  segmentNo: integer("segment_no").notNull().default(1),
  componentCode: text("component_code").notNull(),
  cutNameSnapshot: text("cut_name_snapshot").notNull(),
  requiredQuantity: integer("required_quantity").notNull(),
  availableQuantityAtStart: integer("available_quantity_at_start").notNull(),
  additionalNeeded: integer("additional_needed").notNull(),
  productionTarget: integer("production_target").notNull(),
  producedQuantity: integer("produced_quantity").notNull().default(0),
  traceabilityNo: text("traceability_no").notNull().references(() => traceabilityRecords.traceabilityNo),
  origin: text("origin").notNull().default(""),
  slaughterhouse: text("slaughterhouse").notNull().default(""),
  cattleType: text("cattle_type").notNull().default(""),
  grade: text("grade").notNull().default(""),
  storageMethod: text("storage_method").notNull().default(""),
  expiryText: text("expiry_text").notNull().default(""),
  packagingMaterial: text("packaging_material").notNull().default(""),
  foodType: text("food_type").notNull().default(""),
  status: text("status").notNull().default("in_progress"),
  startedBy: text("started_by").notNull(),
  startedAt: text("started_at").notNull(),
  completedAt: text("completed_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_production_batches_date_component").on(table.productionDate, table.componentCode, table.status),
  uniqueIndex("idx_production_batches_parent_segment").on(table.parentBatchId, table.segmentNo),
  check("production_batches_required_nonnegative", sql`${table.requiredQuantity} >= 0`),
  check("production_batches_available_nonnegative", sql`${table.availableQuantityAtStart} >= 0`),
  check("production_batches_additional_nonnegative", sql`${table.additionalNeeded} >= 0`),
  check("production_batches_target_nonnegative", sql`${table.productionTarget} >= 0`),
  check("production_batches_produced_nonnegative", sql`${table.producedQuantity} >= 0`),
  check("production_batches_status_valid", sql`${table.status} in ('planned', 'in_progress', 'completed', 'cancelled')`),
]);

export const skinPacks = sqliteTable("skin_packs", {
  id: text("id").primaryKey(),
  productionBatchId: text("production_batch_id").notNull().references(() => productionBatches.id),
  batchSequence: integer("batch_sequence").notNull(),
  skinPackCode: text("skin_pack_code").notNull().unique(),
  componentCode: text("component_code").notNull(),
  cutNameSnapshot: text("cut_name_snapshot").notNull(),
  weightG: integer("weight_g").notNull(),
  traceabilityNo: text("traceability_no").notNull().references(() => traceabilityRecords.traceabilityNo),
  origin: text("origin").notNull().default(""),
  slaughterhouse: text("slaughterhouse").notNull().default(""),
  cattleType: text("cattle_type").notNull().default(""),
  grade: text("grade").notNull().default(""),
  manufacturedAt: text("manufactured_at").notNull(),
  storageMethod: text("storage_method").notNull().default(""),
  expiryText: text("expiry_text").notNull().default(""),
  packagingMaterial: text("packaging_material").notNull().default(""),
  foodType: text("food_type").notNull().default(""),
  status: text("status").notNull().default("available"),
  idempotencyKey: text("idempotency_key").notNull().unique(),
  createdBy: text("created_by").notNull(),
  assignedAt: text("assigned_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("idx_skin_packs_batch_sequence").on(table.productionBatchId, table.batchSequence),
  index("idx_skin_packs_available_component").on(table.componentCode, table.status, table.createdAt),
  index("idx_skin_packs_batch").on(table.productionBatchId, table.createdAt),
  check("skin_packs_weight_positive", sql`${table.weightG} > 0`),
  check("skin_packs_status_valid", sql`${table.status} in ('available', 'assigned', 'voided', 'consumed')`),
]);

export const skinPackLabels = sqliteTable("skin_pack_labels", {
  id: text("id").primaryKey(),
  skinPackId: text("skin_pack_id").notNull().references(() => skinPacks.id),
  version: integer("version").notNull(),
  status: text("status").notNull().default("draft"),
  payloadJson: text("payload_json").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull(),
  printedBy: text("printed_by"),
  printedAt: text("printed_at"),
  voidedBy: text("voided_by"),
  voidedAt: text("voided_at"),
  voidReason: text("void_reason"),
}, (table) => [
  uniqueIndex("idx_skin_pack_labels_version").on(table.skinPackId, table.version),
  index("idx_skin_pack_labels_status").on(table.skinPackId, table.status),
  check("skin_pack_labels_status_valid", sql`${table.status} in ('draft', 'printed', 'void')`),
]);

export const packages = sqliteTable("packages", {
  id: text("id").primaryKey(),
  workItemId: text("work_item_id").references(() => workItems.id),
  packageSequence: integer("package_sequence"),
  assemblyKey: text("assembly_key"),
  packageCode: text("package_code").notNull().unique(),
  productId: text("product_id").notNull().references(() => products.id),
  productNameSnapshot: text("product_name_snapshot").notNull(),
  packageStatus: text("package_status").notNull().default("queued"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_packages_work_item").on(table.workItemId),
  uniqueIndex("idx_packages_work_item_sequence").on(table.workItemId, table.packageSequence),
  uniqueIndex("idx_packages_assembly_key").on(table.assemblyKey),
  index("idx_packages_status").on(table.packageStatus),
]);

export const packageSkinPacks = sqliteTable("package_skin_packs", {
  id: text("id").primaryKey(),
  packageId: text("package_id").notNull().references(() => packages.id),
  skinPackId: text("skin_pack_id").notNull().references(() => skinPacks.id),
  productComponentId: text("product_component_id").notNull(),
  quantitySlot: integer("quantity_slot").notNull().default(1),
  assignedBy: text("assigned_by").notNull(),
  assignedAt: text("assigned_at").notNull(),
}, (table) => [
  uniqueIndex("idx_package_skin_packs_skin_pack").on(table.skinPackId),
  uniqueIndex("idx_package_skin_packs_component_slot").on(table.packageId, table.productComponentId, table.quantitySlot),
  index("idx_package_skin_packs_package").on(table.packageId, table.assignedAt),
]);
